export const FETCHING_CITY_DETAILS = 'FETCHING_CITY_DETAILS'
export const FETCHING_CITY_DETAILS_SUCCESS = 'FETCHING_CITY_DETAILS_SUCCESS'
export const FETCHING_CITY_DETAILS_FAILURE = 'FETCHING_CITY_DETAILS_FAILURE'

export const FETCHING_WEATHER = 'FETCHING_WEATHER'
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS'
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE'

export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'